# GENERATED from pkg/protocol §19 -- do not edit. Regenerate: `go generate ./...` in kernel/pkg/protocol.
CODES = {
    "E_BUSY_TIMEOUT": -32015,
    "E_DEPS_HASH_MISMATCH": -32014,
    "E_DEPS_INSTALL_FAILED": -32008,
    "E_DEPS_MISSING": -32007,
    "E_HANDSHAKE_REJECTED": -32012,
    "E_HANDSHAKE_TIMEOUT": -32011,
    "E_HOTKEY_CONFLICT": -32006,
    "E_IO": -32010,
    "E_METHOD_NOT_FOUND": -32601,
    "E_MODEL_LOAD_TIMEOUT": -32017,
    "E_PARSE": -32700,
    "E_PERMISSION_DENIED": -32005,
    "E_PLUGIN_CRASHED": -32002,
    "E_PLUGIN_DOWN": -32000,
    "E_PLUGIN_MISSING": -32003,
    "E_PLUGIN_STATE": -32004,
    "E_STDOUT_CONTAMINATED": -32013,
    "E_STREAM_CLOSED": -32009,
    "E_TIMEOUT": -32001,
    "E_TOOL_UNAVAILABLE": -32016,
    "E_VRAM_INSUFFICIENT": -32018,
}
MESSAGES = {
    "E_BUSY_TIMEOUT": "busy deadline exceeded and ping unresponsive",
    "E_DEPS_HASH_MISMATCH": "dependency lock hash mismatch",
    "E_DEPS_INSTALL_FAILED": "dependency install failed",
    "E_DEPS_MISSING": "dependency not installed",
    "E_HANDSHAKE_REJECTED": "handshake rejected (bad token/version)",
    "E_HANDSHAKE_TIMEOUT": "handshake timed out",
    "E_HOTKEY_CONFLICT": "hotkey conflict",
    "E_IO": "io error",
    "E_METHOD_NOT_FOUND": "method not found",
    "E_MODEL_LOAD_TIMEOUT": "model load exceeded timeout",
    "E_PARSE": "parse error",
    "E_PERMISSION_DENIED": "permission denied",
    "E_PLUGIN_CRASHED": "plugin crashed",
    "E_PLUGIN_DOWN": "plugin process not running",
    "E_PLUGIN_MISSING": "plugin not found",
    "E_PLUGIN_STATE": "plugin invalid state",
    "E_STDOUT_CONTAMINATED": "stdout contaminated with non-JSON data",
    "E_STREAM_CLOSED": "stream closed or missing",
    "E_TIMEOUT": "call timeout",
    "E_TOOL_UNAVAILABLE": "tool unavailable (locate failed)",
    "E_VRAM_INSUFFICIENT": "insufficient VRAM with no usable fallback",
}
DIAG_BY_CODE = {
    -32015: "E_BUSY_TIMEOUT",
    -32014: "E_DEPS_HASH_MISMATCH",
    -32008: "E_DEPS_INSTALL_FAILED",
    -32007: "E_DEPS_MISSING",
    -32012: "E_HANDSHAKE_REJECTED",
    -32011: "E_HANDSHAKE_TIMEOUT",
    -32006: "E_HOTKEY_CONFLICT",
    -32010: "E_IO",
    -32601: "E_METHOD_NOT_FOUND",
    -32017: "E_MODEL_LOAD_TIMEOUT",
    -32700: "E_PARSE",
    -32005: "E_PERMISSION_DENIED",
    -32002: "E_PLUGIN_CRASHED",
    -32000: "E_PLUGIN_DOWN",
    -32003: "E_PLUGIN_MISSING",
    -32004: "E_PLUGIN_STATE",
    -32013: "E_STDOUT_CONTAMINATED",
    -32009: "E_STREAM_CLOSED",
    -32001: "E_TIMEOUT",
    -32016: "E_TOOL_UNAVAILABLE",
    -32018: "E_VRAM_INSUFFICIENT",
}
